INSERT INTO "tour" ("hotel_name", "region", "board_types", "transport_types", "departure_destinations") VALUES
('Hotel Oasis Atlantico Belorizonte', 'Wyspy Zielonego Przylądka / Sal / Santa Maria (sal)', 'All inclusive', 'plane', 'Warszawa'),
('Hotel Serra Palace (ex. LTI Serra Resort)', 'Turcja / Side / Kızılot', 'All inclusive 24h', 'plane', 'Bydgoszcz,Gdańsk,Kraków,Katowice,Łódź,Poznań,Rzeszów,Szczecin,Warszawa,Wrocław'),
('Hotel Fuerteventura Princess', 'Wyspy Kanaryjskie / Fuerteventura / Esquinzo', 'All inclusive', 'plane', 'Gdańsk,Katowice,Poznań,Warszawa,Wrocław'),
('Hotel Grand Blue Fafa', 'Albania / Durres / Golem', 'All inclusive', 'own,plane', 'Gdańsk,Katowice,Kraków,Poznań,Rzeszów,Warszawa,Wrocław'),
('Hotel Strand Taba Heights Beach & Golf Resort (ex. InterContinental)', 'Egipt / Taba', 'All inclusive', 'plane', 'Katowice,Warszawa,Wrocław'),
('Hotel Blue Lagoon Garden Satellite', 'Grecja / Kos / Lambi', 'All inclusive', 'plane', 'Katowice,Poznań,Warszawa,Wrocław'),
('Hotel Panorama Boutique Village', 'Grecja / Kreta / Agia Pelagia', 'All inclusive', 'plane', 'Gdańsk,Katowice,Poznań,Warszawa,Wrocław'),
('Hotel Grand Sahin’s Gumuldur Resort', 'Turcja / Kusadasi / Gumuldur', 'All inclusive', 'plane', 'Katowice,Warszawa'),
('Hotel Acharavi Mare', 'Grecja / Korfu / Acharavi', 'All inclusive', 'plane', 'Gdańsk,Katowice,Poznań,Warszawa,Wrocław'),
('Hotel Blue Sea Beach Resort', 'Grecja / Rodos / Faliraki', 'All inclusive', 'plane', 'Gdańsk,Katowice,Kraków,Łódź,Poznań,Warszawa,Wrocław'),
('Hotel Sensitive Premium Resort & Spa', 'Turcja / Belek / Boğazkent', 'All inclusive ultra', 'plane', 'Bydgoszcz,Gdańsk,Katowice,Kraków,Łódź,Poznań,Rzeszów,Szczecin,Warszawa,Wrocław'),
('Hotel Ascos Coral Beach', 'Cypr / Pafos', 'All inclusive', 'plane', 'Gdańsk,Katowice,Kraków,Warszawa - Modlin,Wrocław'),
('Hotel Grint', 'Albania / Durres / Golem', 'All inclusive', 'plane', 'Gdańsk,Katowice,Kraków,Poznań,Rzeszów,Warszawa,Wrocław'),
('J’adore Deluxe Hotel & Spa', 'Turcja / Side', 'All inclusive ultra 24h', 'plane', 'Bydgoszcz,Gdańsk,Katowice,Kraków,Łódź,Poznań,Rzeszów,Szczecin,Warszawa,Wrocław'),
('Hotel Oasis Atlantico Belorizonte', 'Wyspy Zielonego Przylądka / Sal / Santa Maria (sal)', 'All inclusive', 'plane', 'Warszawa'),
('Hotel Rodos Palace Luxury Convention Resort', 'Grecja / Rodos / Ixia', ' All inclusive', 'plane', 'Gdańsk,Katowice,Kraków,Łódź,Poznań,Warszawa,Wrocław'),
('Hotel Club Cactus Paradise', 'Turcja / Kusadasi / Gumuldur', 'All inclusive', 'plane', 'Katowice,Warszawa'),
('Hotel Vikingen Infinity Resort & Spa', 'Turcja / Alanya / Okurcalar', 'All inclusive', 'plane', 'Bydgoszcz,Gdańsk,Katowice,Kraków,Łódź,Poznań,Rzeszów,Szczecin,Warszawa,Wrocław'),
('Hotel Villaggio Albergo Belmonte', 'Włochy / Kalabria / Belmonte Calabro', 'Full board plus', 'plane', 'Katowice,Warszawa,Wrocław'),
('Hotel Xenios Anastasia Resort & Spa', 'Grecja / Chalkidiki / Nea Skioni', 'All inclusive ultra ', 'own', ''),
('Hotel Dream Water World', 'Turcja / Side', 'All inclusive', 'plane', 'Bydgoszcz,Gdańsk,Katowice,Kraków,Łódź,Poznań,Rzeszów,Szczecin,Warszawa,Wrocław'),
('Hotel Castello Mare & Wellness Resort', 'Gruzja / Adżaria / Tsikhisdziri', 'All inclusive', 'plane', 'Katowice,Kraków,Warszawa,Wrocław'),
('Hotel Horizont', 'Albania / Durres', 'All inclusive', 'own,plane', 'Gdańsk,Katowice,Kraków,Poznań,Rzeszów,Warszawa,Wrocław'),
('Apartamenty Kanegra Plava Laguna', 'Chorwacja / Istria / Kanegra', 'Bez wyżywienia,Śniadania,2 posiłki', 'own', ''),
('Hotel Q Premium', 'Turcja / Alanya / Okurcalar', 'All inclusive ultra 24h', 'plane', 'Bydgoszcz,Gdańsk,Katowice,Kraków,Łódź,Poznań,Rzeszów,Szczecin,Warszawa,Wrocław'),
('Hotel Ramada Resort Akbuk', 'Turcja / Didyma / Akbuk', 'All inclusive 24h', 'plane', 'Katowice,Poznań,Warszawa,Wrocław'),
('Hotel Mirador Maspalomas by Dunas', 'Wyspy Kanaryjskie / Gran Canaria / Maspalomas', 'All inclusive', 'plane', 'Katowice,Poznań,Warszawa,Wrocław'),
('Hotel Royal Karthago Djerba', 'Tunezja / Djerba / Dżerba', 'All inclusive', 'plane', 'Katowice,Poznań,Warszawa,Wrocław'),
('Hotel Maxeria Blue Didyma', 'Turcja / Didyma / Akbuk', 'All inclusive ultra 24h', 'plane', 'Katowice,Poznań,Warszawa,Wrocław'),
('Hotel Fafa Premium', 'Albania / Durres / Golem', 'All inclusive', 'own,plane', 'Gdańsk,Katowice,Kraków,Poznań,Rzeszów,Warszawa,Wrocław'),
('Hotel Blue Lagoon Resort', 'Grecja / Kos / Lambi', 'All inclusive', 'plane', 'Katowice,Poznań,Warszawa,Wrocław'),
('Hotel Domina Zagarella Sicily', 'Włochy / Sycylia / Santa Flavia', 'All inclusive soft', 'plane', 'Katowice,Warszawa'),
('Alarcha Hotels & Resorts', 'Turcja / Side / Manavgat', 'All inclusive ultra 24 h', 'plane', 'Bydgoszcz,Gdańsk,Katowice,Kraków,Łódź,Poznań,Rzeszów,Szczecin,Warszawa,Wrocław'),
('Caprici Beach Hotel & SPA', 'Hiszpania / Costa Brava / Santa Susanna', '2 posiłki', 'plane', 'Katowice,Warszawa,Wrocław'),
('Hotel R2 Pajara Beach', 'Wyspy Kanaryjskie / Fuerteventura / Costa Calma', 'All inclusive', 'plane', 'Gdańsk,Katowice,Poznań,Warszawa,Wrocław'),
('Hotel Presa Di Finica (ex. Fun & Sun Club Di Finica)', 'Turcja / Finike', 'All inclusive', 'plane', 'Bydgoszcz,Gdańsk,Katowice,Kraków,Łódź,Poznań,Rzeszów,Szczecin,Warszawa,Wrocław'),
('Hotel Azure by Yelken', 'Turcja / Bodrum / Turgutreis', 'All inclusive ultra 24h', 'plane', 'Katowice,Poznań,Warszawa,Wrocław'),
('Hotel Monte Mar Palace', 'Madera / Ponta Delgada', '2 posiłki,All inclusive', 'plane', 'Katowice,Poznań,Warszawa,Wrocław'),
('Hotel Solimar Aquamarine', 'Grecja / Kreta / Pirgos Psilonerou', 'All inclusive', 'plane', 'Gdańsk,Katowice,Poznań,Warszawa,Wrocław'),
('Hotel Kadikale Resort Spa & Wellness', 'Turcja / Bodrum / Turgutreis', 'All inclusive', 'plane', 'Katowice,Poznań,Warszawa,Wrocław'),
('Hotel Aquasis Deluxe Resort & Spa', 'Turcja / Didyma / Didim', ' All Inclusive ultra 24h', 'plane', 'Katowice,Poznań,Warszawa,Wrocław'),
('Resort Amarin Apartments', 'Chorwacja / Istria / Rovinj', 'Bez wyżywienia', 'own', ''),
('Hotel Occidental Cala Viñas', 'Hiszpania / Majorka / Cala Vinas', 'All inclusive', 'plane', 'Gdańsk,Katowice,Poznań,Warszawa,Wrocław'),
('Hotel Intercontinental Mauritius', 'Mauritius / Wybrzeże Północne / Balaclava', 'All inclusive', 'plane', 'Warszawa'),
('Paradise Bay Resort', 'Malta / Wyspa Malta / Cirkewwa', 'Śniadania,2 posiłki,All inclusive soft', 'plane', 'Gdańsk,Katowice,Kraków,Poznań,Warszawa,Warszawa - Modlin,Wrocław'),
('Hotel Pine Bay', 'Turcja / Kusadasi', 'All inclusive 24h', 'plane', 'Katowice,Warszawa'),
('Hotel VidaMar Resort Madeira', 'Madera / Funchal', '2 posiłki,All inclusive soft', 'plane', 'Katowice,Poznań,Warszawa,Wrocław'),
('Hotel Club Boran Mare Beach', 'Turcja / Kemer / Goynuk', 'All inclusive', 'plane', 'Bydgoszcz,Gdańsk,Katowice,Kraków,Łódź,Poznań,Rzeszów,Szczecin,Warszawa,Wrocław'),
('Hotel Gaia Royal', 'Grecja / Kos / Mastichari', 'All inclusive', 'plane', 'Katowice,Poznań,Warszawa,Wrocław'),
('Hotel BG Portinatx Beach Club', 'Hiszpania / Ibiza / Portinatx', '2 posiłki,All inclusive', 'plane', 'Katowice'),
('Hotel Club Esse Palmasera Resort', 'Włochy / Sardynia / Cala Gonone', 'All inclusive', 'plane', 'Katowice,Warszawa'),
('Hotel Magna Graecia', 'Grecja / Korfu / Dassia', 'All inclusive', 'plane', 'Gdańsk,Katowice,Poznań,Warszawa,Wrocław'),
('Hotel Blue Dream Palace', 'Grecja / Thassos / Limenaria', '2 posiłki', 'plane', 'Katowice,Warszawa'),
('Hotel Lazuli', 'Egipt / Marsa Alam / Al-kusajr', 'All inclusive', 'plane', 'Gdańsk,Katowice,Poznań,Warszawa,Wrocław'),
('Hotel Iberostar Slavija', 'Czarnogóra / Riwiera Czarnogórska / Budva', 'Śniadania,2 posiłki', 'own', ''),
('Hotel Angela Beach', 'Grecja / Korfu / Astrakeri', 'All inclusive', 'plane', 'Gdańsk,Katowice,Poznań,Warszawa,Wrocław'),
('Hotel Grecotel Filoxenia', 'Grecja / Peloponez / Kalamata', 'Śniadania,2 posiłki', 'own', ''),
('Hotel Santa Caterina Village Resort & Spa', 'Włochy / Kalabria / Scalea', 'All inclusive', 'plane', 'Katowice,Warszawa,Wrocław'),
('Hotel BG Pamplona', 'Hiszpania / Majorka / Can Pastilla', '2 posiłki', 'plane', 'Gdańsk,Katowice,Poznań,Warszawa,Wrocław'),
('Hotel Aldemar Royal Olympian', 'Grecja / Peloponez / Skafidia', 'All inclusive premium', 'plane', 'Warszawa'),
('Hotel Estalagem do Mar', 'Madera / Sao Vicente', '2 posiłki,Half board plus', 'plane', 'Katowice,Poznań,Warszawa,Wrocław'),
('Hotel 4R Gran Europe', 'Hiszpania / Costa Dorada / Coma-ruga', '2 posiłki,All inclusive', 'plane', 'Katowice,Warszawa,Wrocław'),
('Hotel Abora Interclub Atlantic', 'Wyspy Kanaryjskie / Gran Canaria / San Agustin', 'All inclusive 24h', 'plane', 'Katowice,Poznań,Warszawa,Wrocław'),
('Hotel VIK Gran Costa Del Sol', 'Hiszpania / Costa del Sol / Cala De Mijas', '2 posiłki,All inclusive', 'plane', 'Katowice,Warszawa'),
('Hotel VidaMar Resort Algarve', 'Portugalia / Algarve / Salgados', '2 posiłki', 'plane', 'Katowice,Warszawa'),
('Hotel Meliá Sunny Beach', 'Bułgaria / Słoneczny Brzeg', 'All inclusive', 'own,plane', 'Katowice,Poznań,Warszawa,Wrocław'),
('Hotel Azure Resort & Spa', 'Grecja / Zakynthos / Planos', 'All inclusive', 'plane', 'Katowice,Poznań,Rzeszów,Warszawa,Wrocław'),
('Santo Miramare Resort', 'Grecja / Santorini / Agios Georgios', 'Śniadania,2 posiłki', 'plane', 'Gdańsk,Kraków,Warszawa'),
('Hotel Flower Garden', 'Albania / Durres / Golem', ' All inclusive premium', 'own', ''),
('Hotel Cabanas Golden Club', 'Portugalia / Algarve / Cabanas', 'All inclusive', 'plane', 'Katowice,Warszawa'),
('Hotel Andon Lapa', 'Albania / Saranda', 'All inclusive', 'own,plane', 'Gdańsk,Katowice,Poznań,Warszawa,Wrocław'),
('Hotel Palma', 'Albania / Saranda', '2 posiłki', 'own,plane', 'Gdańsk,Katowice,Poznań,Warszawa,Wrocław'),
('Hotel Flora Garden Ephesus', 'Turcja / Kusadasi', 'All inclusive', 'plane', 'Katowice,Warszawa'),
('Hotel Porto Evia Boutique', 'Grecja / Evia / Eretria', 'Bez wyżywienia,Śniadania,2 posiłki', 'own', ''),
('Hotel King Evelthon Beach & Resort', 'Cypr / Pafos', 'All inclusive', 'plane', 'Gdańsk,Katowice,Kraków,Warszawa - Modlin,Wrocław'),
('Hotel Mistral Mare', 'Grecja / Kreta / Istro', 'All inclusive', 'plane', 'Gdańsk,Katowice,Poznań,Warszawa,Wrocław'),
('Hotel Calypso', 'Malta / Wyspa Gozo / Marsalforn', 'Śniadania,2 posiłki', 'plane', 'Gdańsk,Katowice,Kraków,Poznań,Warszawa,Warszawa - Modlin,Wrocław'),
('Hotel Odysee Resort', 'Tunezja / Djerba / Dżardżis', 'All inclusive', 'plane', 'Katowice,Poznań,Warszawa,Wrocław'),
('Apartamentos THe Morromar', 'Wyspy Kanaryjskie / Lanzarote / Puerto Del Carmen', 'All inclusive', 'plane', 'Katowice,Warszawa,Wrocław'),
('Hotel Costa Verde', 'Włochy / Sycylia / Cefalu', '2 posiłki,All inclusive soft,All inclusive', 'plane', 'Katowice,Warszawa'),
('Hotel Mogan Princess & Beach Club', 'Wyspy Kanaryjskie / Gran Canaria / Playa De Taurito', 'All inclusive', 'plane', 'Katowice,Poznań,Warszawa,Wrocław'),
('Hotel Messonghi Beach Holiday Resort', 'Grecja / Korfu / Moraitika', ' All inclusive', 'plane', 'Gdańsk,Katowice,Poznań,Warszawa,Wrocław'),
('Hotel Best Western Galaxy', 'Grecja / Zakynthos / Laganas', 'All inclusive', 'plane', 'Katowice,Poznań,Rzeszów,Warszawa,Wrocław'),
('Hotel Residence Le Playe', 'Włochy / Kalabria / Tropea', '2 posiłki', 'plane', 'Katowice,Warszawa,Wrocław'),
('Hotel Veronica', 'Cypr / Pafos', 'Full board plus', 'plane', 'Gdańsk,Katowice,Kraków,Warszawa - Modlin,Wrocław'),
('Hotel Pelagos Zante', 'Grecja / Zakynthos / Tragaki', 'All inclusive', 'plane', 'Katowice,Poznań,Rzeszów,Warszawa,Wrocław'),
('Hotel Golden Coast Family Resort', 'Grecja / Zakynthos / Drosia', 'All inclusive', 'plane', 'Katowice,Poznań,Rzeszów,Warszawa,Wrocław'),
('Hotel Oasis Atlantico Salinas Sea', 'Wyspy Zielonego Przylądka / Sal / Santa Maria (sal)', 'All inclusive 24h', 'plane', 'Warszawa'),
('Hotel BG Tonga Design & Suites Tower', 'Hiszpania / Majorka / Can Picafort', 'All inclusive premium ', 'plane', 'Gdańsk,Katowice,Poznań,Warszawa,Wrocław'),
('Hotel Xenios Dolphin Beach', 'Grecja / Chalkidiki / Possidi', 'All inclusive', 'own', ''),
('Hotel Zita Beach Resort Zarzis', 'Tunezja / Djerba / Dżardżis', 'All inclusive', 'plane', 'Katowice,Poznań,Warszawa,Wrocław'),
('Hotel Prestige Resort', 'Albania / Durres / Golem', 'All inclusive', 'plane', 'Gdańsk,Katowice,Kraków,Poznań,Rzeszów,Warszawa,Wrocław'),
('Hotel Delfino Beach', 'Włochy / Sycylia / Marsala', 'All inclusive soft', 'plane', 'Katowice,Warszawa'),
('Hotel Gloria Palace Royal & Spa', 'Wyspy Kanaryjskie / Gran Canaria / Puerto Rico', '2 posiłki,All inclusive premium', 'plane', 'Katowice,Poznań,Warszawa,Wrocław'),
('Hotel Tabaiba Princess', 'Wyspy Kanaryjskie / Gran Canaria / Maspalomas', 'All inclusive', 'plane', 'Katowice,Poznań,Warszawa,Wrocław'),
('Hotel Simantro Beach', 'Grecja / Chalkidiki / Sani', 'All inclusive', 'own', ''),
('Hotel Aqua Sol Holiday Village', 'Cypr / Pafos', 'All inclusive', 'plane', 'Gdańsk,Katowice,Kraków,Warszawa - Modlin,Wrocław'),
('Hotel Grand Teguise Playa', 'Wyspy Kanaryjskie / Lanzarote / Costa Teguise', 'All inclusive', 'plane', 'Katowice,Warszawa'),
('Hotel Coral Cotillo Beach', 'Wyspy Kanaryjskie / Fuerteventura / El Cotillo', 'Śniadania,2 posiłki', 'plane', 'Gdańsk,Katowice,Poznań,Warszawa,Wrocław'),
('Arche Hotel Poloneza', 'Polska / W mieście / Warszawa', 'Śniadania,2 posiłki', 'own', ''),
('Arche Hotel Puławska Residence', 'Polska / W mieście / Warszawa', 'Śniadania,2 posiłki', 'own', ''),
('Hotel Holiday Inn Express Rzeszów Airport', 'Polska / Przy lotnisku / Jasionka', 'Śniadania', 'own', ''),
('Hotel Hampton By Hilton Warsaw Airport', 'Polska / Przy lotnisku / Warszawa', 'Śniadania', 'own', ''),
('Hotel Altus Poznań Old Town', 'Polska / W mieście / Poznań', 'Śniadania', 'own', ''),
('Western Camp Resort i park rozrywki ENERGYLANDIA', 'Polska / Poza miastem / Zator', 'Śniadania,2 posiłki', 'own', ''),
('Hotel Hampton by Hilton Gdańsk Airport', 'Polska / Przy lotnisku / Gdańsk', 'Śniadania', 'own', ''),
('Hotel Focus Premium Elbląg', 'Polska / W mieście / Elbląg', 'Śniadania,2 posiłki', 'own', ''),
('Apartamenty Świnoujście', 'Polska / Morze / Świnoujście', 'Bez wyżywienia,Śniadania,2 posiłki', 'own', ''),
('Apartamenty Górna Resort', 'Polska / Góry / Szklarska Poręba', 'Bez wyżywienia,Śniadania,2 posiłki', 'own', ''),
('Hotel Courtyard by Marriott Warsaw Airport', 'Polska / Przy lotnisku / Warszawa', 'Śniadania', 'own', ''),
('Apartamenty Sosnowa 4', 'Polska / Morze / Mielno', 'Bez wyżywienia,Śniadania,2 posiłki', 'own', ''),
('Apartamenty Olympic Park', 'Polska / Morze / Kołobrzeg', 'Bez wyżywienia,Śniadania,2 posiłki', 'own', ''),
('Regent Warsaw Hotel', 'Polska / W mieście / Warszawa', 'Śniadania', 'own', ''),
('Hotel Wellness Harrachovka', 'Czechy / Czeskie Karkonosze / Harrachov', '2 posiłki', 'own', ''),
('Hotel Renaissance Warsaw Airport', 'Polska / Przy lotnisku / Warszawa', 'Śniadania', 'own', ''),
('Hotel Piotr SPA &Wellness', 'Polska / Góry / Boguszów-gorce', 'Śniadania,2 posiłki', 'own', ''),
('Hotel Redyk Ski & Relax', 'Polska / Góry / Ząb', 'Śniadania,2 posiłki', 'own', ''),
('Hotel Srní', 'Czechy / Szumawy / Srni', 'Śniadania,2 posiłki', 'own', ''),
('Apartamenty Ostróda', 'Polska / Jeziora / Ostróda', 'Śniadania', 'own', ''),
('NAT Krynica Morska', 'Polska / Morze / Krynica Morska', 'Śniadania,2 posiłki', 'own', ''),
('Hotel Clarion', 'Czechy (narty) / Czeskie Karkonosze / Szpindlerowy Młyn', 'Śniadania,2 posiłki', 'own', ''),
('Osada Górski Potok', 'Polska / Góry / Szczawina', 'Śniadania,2 posiłki,All inclusive', 'own', ''),
('Focus Hotel Gdańsk', 'Polska / Morze / Gdańsk', 'Śniadania,2 posiłki', 'own', ''),
('Hotel Las', 'Polska / Góry / Piechowice', 'Śniadania,2 posiłki', 'own', ''),
('Hotel NAT Jarosławiec', 'Polska / Morze / Jarosławiec', 'Śniadania,2 posiłki', 'own', ''),
('Focus Hotel Premium Sopot', 'Polska / Morze / Sopot', 'Śniadania,2 posiłki', 'own', '');
