INSERT INTO "tour" ("hotel_name", "region", "own_transport", "board_types") VALUES
('Hotel Oasis Atlantico Belorizonte', 'Wyspy Zielonego Przylądka / Sal / Santa Maria (sal)', 'False', 'All inclusive'),
('Hotel Serra Palace (ex. LTI Serra Resort)', 'Turcja / Side / Kızılot', 'False', 'All inclusive 24h'),
('Hotel Fuerteventura Princess', 'Wyspy Kanaryjskie / Fuerteventura / Esquinzo', 'False', 'All inclusive'),
('Hotel Grand Blue Fafa', 'Albania / Durres / Golem', 'True', 'All inclusive'),
('Hotel Strand Taba Heights Beach & Golf Resort (ex. InterContinental)', 'Egipt / Taba', 'False', 'All inclusive'),
('Hotel Blue Lagoon Garden Satellite', 'Grecja / Kos / Lambi', 'False', 'All inclusive'),
('Hotel Panorama Boutique Village', 'Grecja / Kreta / Agia Pelagia', 'False', 'All inclusive'),
('Hotel Grand Sahin’s Gumuldur Resort', 'Turcja / Kusadasi / Gumuldur', 'False', 'All inclusive'),
('Hotel Acharavi Mare', 'Grecja / Korfu / Acharavi', 'False', 'All inclusive'),
('Hotel Blue Sea Beach Resort', 'Grecja / Rodos / Faliraki', 'False', 'All inclusive'),
('Hotel Sensitive Premium Resort & Spa', 'Turcja / Belek / Boğazkent', 'False', 'All inclusive ultra'),
('Hotel Ascos Coral Beach', 'Cypr / Pafos', 'False', 'All inclusive'),
('Hotel Grint', 'Albania / Durres / Golem', 'False', 'All inclusive'),
('J’adore Deluxe Hotel & Spa', 'Turcja / Side', 'False', 'All inclusive ultra 24h'),
('Hotel Oasis Atlantico Belorizonte', 'Wyspy Zielonego Przylądka / Sal / Santa Maria (sal)', 'False', 'All inclusive'),
('Hotel Rodos Palace Luxury Convention Resort', 'Grecja / Rodos / Ixia', 'False', ' All inclusive'),
('Hotel Club Cactus Paradise', 'Turcja / Kusadasi / Gumuldur', 'False', 'All inclusive'),
('Hotel Vikingen Infinity Resort & Spa', 'Turcja / Alanya / Okurcalar', 'False', 'All inclusive'),
('Hotel Villaggio Albergo Belmonte', 'Włochy / Kalabria / Belmonte Calabro', 'False', 'Full board plus'),
('Hotel Xenios Anastasia Resort & Spa', 'Grecja / Chalkidiki / Nea Skioni', 'True', 'All inclusive ultra '),
('Hotel Dream Water World', 'Turcja / Side', 'False', 'All inclusive'),
('Hotel Castello Mare & Wellness Resort', 'Gruzja / Adżaria / Tsikhisdziri', 'False', 'All inclusive'),
('Hotel Horizont', 'Albania / Durres', 'True', 'All inclusive'),
('Apartamenty Kanegra Plava Laguna', 'Chorwacja / Istria / Kanegra', 'True', 'Bez wyżywienia,Śniadania,2 posiłki'),
('Hotel Q Premium', 'Turcja / Alanya / Okurcalar', 'False', 'All inclusive ultra 24h'),
('Hotel Ramada Resort Akbuk', 'Turcja / Didyma / Akbuk', 'False', 'All inclusive 24h'),
('Hotel Mirador Maspalomas by Dunas', 'Wyspy Kanaryjskie / Gran Canaria / Maspalomas', 'False', 'All inclusive'),
('Hotel Royal Karthago Djerba', 'Tunezja / Djerba / Dżerba', 'False', 'All inclusive'),
('Hotel Maxeria Blue Didyma', 'Turcja / Didyma / Akbuk', 'False', 'All inclusive ultra 24h'),
('Hotel Fafa Premium', 'Albania / Durres / Golem', 'True', 'All inclusive'),
('Hotel Blue Lagoon Resort', 'Grecja / Kos / Lambi', 'False', 'All inclusive'),
('Hotel Domina Zagarella Sicily', 'Włochy / Sycylia / Santa Flavia', 'False', 'All inclusive soft'),
('Alarcha Hotels & Resorts', 'Turcja / Side / Manavgat', 'False', 'All inclusive ultra 24 h'),
('Caprici Beach Hotel & SPA', 'Hiszpania / Costa Brava / Santa Susanna', 'False', '2 posiłki'),
('Hotel R2 Pajara Beach', 'Wyspy Kanaryjskie / Fuerteventura / Costa Calma', 'False', 'All inclusive'),
('Hotel Presa Di Finica (ex. Fun & Sun Club Di Finica)', 'Turcja / Finike', 'False', 'All inclusive'),
('Hotel Azure by Yelken', 'Turcja / Bodrum / Turgutreis', 'False', 'All inclusive ultra 24h'),
('Hotel Monte Mar Palace', 'Madera / Ponta Delgada', 'False', '2 posiłki,All inclusive'),
('Hotel Solimar Aquamarine', 'Grecja / Kreta / Pirgos Psilonerou', 'False', 'All inclusive'),
('Hotel Kadikale Resort Spa & Wellness', 'Turcja / Bodrum / Turgutreis', 'False', 'All inclusive'),
('Hotel Aquasis Deluxe Resort & Spa', 'Turcja / Didyma / Didim', 'False', ' All Inclusive ultra 24h'),
('Resort Amarin Apartments', 'Chorwacja / Istria / Rovinj', 'True', 'Bez wyżywienia'),
('Hotel Occidental Cala Viñas', 'Hiszpania / Majorka / Cala Vinas', 'False', 'All inclusive'),
('Hotel Intercontinental Mauritius', 'Mauritius / Wybrzeże Północne / Balaclava', 'False', 'All inclusive'),
('Paradise Bay Resort', 'Malta / Wyspa Malta / Cirkewwa', 'False', 'Śniadania,2 posiłki,All inclusive soft'),
('Hotel Pine Bay', 'Turcja / Kusadasi', 'False', 'All inclusive 24h'),
('Hotel VidaMar Resort Madeira', 'Madera / Funchal', 'False', '2 posiłki,All inclusive soft'),
('Hotel Club Boran Mare Beach', 'Turcja / Kemer / Goynuk', 'False', 'All inclusive'),
('Hotel Gaia Royal', 'Grecja / Kos / Mastichari', 'False', 'All inclusive'),
('Hotel BG Portinatx Beach Club', 'Hiszpania / Ibiza / Portinatx', 'False', '2 posiłki,All inclusive'),
('Hotel Club Esse Palmasera Resort', 'Włochy / Sardynia / Cala Gonone', 'False', 'All inclusive'),
('Hotel Magna Graecia', 'Grecja / Korfu / Dassia', 'False', 'All inclusive'),
('Hotel Blue Dream Palace', 'Grecja / Thassos / Limenaria', 'False', '2 posiłki'),
('Hotel Lazuli', 'Egipt / Marsa Alam / Al-kusajr', 'False', 'All inclusive'),
('Hotel Iberostar Slavija', 'Czarnogóra / Riwiera Czarnogórska / Budva', 'True', 'Śniadania,2 posiłki'),
('Hotel Angela Beach', 'Grecja / Korfu / Astrakeri', 'False', 'All inclusive'),
('Hotel Grecotel Filoxenia', 'Grecja / Peloponez / Kalamata', 'True', 'Śniadania,2 posiłki'),
('Hotel Santa Caterina Village Resort & Spa', 'Włochy / Kalabria / Scalea', 'False', 'All inclusive'),
('Hotel BG Pamplona', 'Hiszpania / Majorka / Can Pastilla', 'False', '2 posiłki'),
('Hotel Aldemar Royal Olympian', 'Grecja / Peloponez / Skafidia', 'False', 'All inclusive premium'),
('Hotel Estalagem do Mar', 'Madera / Sao Vicente', 'False', '2 posiłki,Half board plus'),
('Hotel 4R Gran Europe', 'Hiszpania / Costa Dorada / Coma-ruga', 'False', '2 posiłki,All inclusive'),
('Hotel Abora Interclub Atlantic', 'Wyspy Kanaryjskie / Gran Canaria / San Agustin', 'False', 'All inclusive 24h'),
('Hotel VIK Gran Costa Del Sol', 'Hiszpania / Costa del Sol / Cala De Mijas', 'False', '2 posiłki,All inclusive'),
('Hotel VidaMar Resort Algarve', 'Portugalia / Algarve / Salgados', 'False', '2 posiłki'),
('Hotel Meliá Sunny Beach', 'Bułgaria / Słoneczny Brzeg', 'True', 'All inclusive'),
('Hotel Azure Resort & Spa', 'Grecja / Zakynthos / Planos', 'False', 'All inclusive'),
('Santo Miramare Resort', 'Grecja / Santorini / Agios Georgios', 'False', 'Śniadania,2 posiłki'),
('Hotel Flower Garden', 'Albania / Durres / Golem', 'True', ' All inclusive premium'),
('Hotel Cabanas Golden Club', 'Portugalia / Algarve / Cabanas', 'False', 'All inclusive'),
('Hotel Andon Lapa', 'Albania / Saranda', 'True', 'All inclusive'),
('Hotel Palma', 'Albania / Saranda', 'True', '2 posiłki'),
('Hotel Flora Garden Ephesus', 'Turcja / Kusadasi', 'False', 'All inclusive'),
('Hotel Porto Evia Boutique', 'Grecja / Evia / Eretria', 'True', 'Bez wyżywienia,Śniadania,2 posiłki'),
('Hotel King Evelthon Beach & Resort', 'Cypr / Pafos', 'False', 'All inclusive'),
('Hotel Mistral Mare', 'Grecja / Kreta / Istro', 'False', 'All inclusive'),
('Hotel Calypso', 'Malta / Wyspa Gozo / Marsalforn', 'False', 'Śniadania,2 posiłki'),
('Hotel Odysee Resort', 'Tunezja / Djerba / Dżardżis', 'False', 'All inclusive'),
('Apartamentos THe Morromar', 'Wyspy Kanaryjskie / Lanzarote / Puerto Del Carmen', 'False', 'All inclusive'),
('Hotel Costa Verde', 'Włochy / Sycylia / Cefalu', 'False', '2 posiłki,All inclusive soft,All inclusive'),
('Hotel Mogan Princess & Beach Club', 'Wyspy Kanaryjskie / Gran Canaria / Playa De Taurito', 'False', 'All inclusive'),
('Hotel Messonghi Beach Holiday Resort', 'Grecja / Korfu / Moraitika', 'False', ' All inclusive'),
('Hotel Best Western Galaxy', 'Grecja / Zakynthos / Laganas', 'False', 'All inclusive'),
('Hotel Residence Le Playe', 'Włochy / Kalabria / Tropea', 'False', '2 posiłki'),
('Hotel Veronica', 'Cypr / Pafos', 'False', 'Full board plus'),
('Hotel Pelagos Zante', 'Grecja / Zakynthos / Tragaki', 'False', 'All inclusive'),
('Hotel Golden Coast Family Resort', 'Grecja / Zakynthos / Drosia', 'False', 'All inclusive'),
('Hotel Oasis Atlantico Salinas Sea', 'Wyspy Zielonego Przylądka / Sal / Santa Maria (sal)', 'False', 'All inclusive 24h'),
('Hotel BG Tonga Design & Suites Tower', 'Hiszpania / Majorka / Can Picafort', 'False', 'All inclusive premium '),
('Hotel Xenios Dolphin Beach', 'Grecja / Chalkidiki / Possidi', 'True', 'All inclusive'),
('Hotel Zita Beach Resort Zarzis', 'Tunezja / Djerba / Dżardżis', 'False', 'All inclusive'),
('Hotel Prestige Resort', 'Albania / Durres / Golem', 'False', 'All inclusive'),
('Hotel Delfino Beach', 'Włochy / Sycylia / Marsala', 'False', 'All inclusive soft'),
('Hotel Gloria Palace Royal & Spa', 'Wyspy Kanaryjskie / Gran Canaria / Puerto Rico', 'False', '2 posiłki,All inclusive premium'),
('Hotel Tabaiba Princess', 'Wyspy Kanaryjskie / Gran Canaria / Maspalomas', 'False', 'All inclusive'),
('Hotel Simantro Beach', 'Grecja / Chalkidiki / Sani', 'True', 'All inclusive'),
('Hotel Aqua Sol Holiday Village', 'Cypr / Pafos', 'False', 'All inclusive'),
('Hotel Grand Teguise Playa', 'Wyspy Kanaryjskie / Lanzarote / Costa Teguise', 'False', 'All inclusive'),
('Hotel Coral Cotillo Beach', 'Wyspy Kanaryjskie / Fuerteventura / El Cotillo', 'False', 'Śniadania,2 posiłki'),
('Arche Hotel Poloneza', 'Polska / W mieście / Warszawa', 'True', 'Śniadania,2 posiłki'),
('Arche Hotel Puławska Residence', 'Polska / W mieście / Warszawa', 'True', 'Śniadania,2 posiłki'),
('Hotel Holiday Inn Express Rzeszów Airport', 'Polska / Przy lotnisku / Jasionka', 'True', 'Śniadania'),
('Hotel Hampton By Hilton Warsaw Airport', 'Polska / Przy lotnisku / Warszawa', 'True', 'Śniadania'),
('Hotel Altus Poznań Old Town', 'Polska / W mieście / Poznań', 'True', 'Śniadania'),
('Western Camp Resort i park rozrywki ENERGYLANDIA', 'Polska / Poza miastem / Zator', 'True', 'Śniadania,2 posiłki'),
('Hotel Hampton by Hilton Gdańsk Airport', 'Polska / Przy lotnisku / Gdańsk', 'True', 'Śniadania'),
('Hotel Focus Premium Elbląg', 'Polska / W mieście / Elbląg', 'True', 'Śniadania,2 posiłki'),
('Apartamenty Świnoujście', 'Polska / Morze / Świnoujście', 'True', 'Bez wyżywienia,Śniadania,2 posiłki'),
('Apartamenty Górna Resort', 'Polska / Góry / Szklarska Poręba', 'True', 'Bez wyżywienia,Śniadania,2 posiłki'),
('Hotel Courtyard by Marriott Warsaw Airport', 'Polska / Przy lotnisku / Warszawa', 'True', 'Śniadania'),
('Apartamenty Sosnowa 4', 'Polska / Morze / Mielno', 'True', 'Bez wyżywienia,Śniadania,2 posiłki'),
('Apartamenty Olympic Park', 'Polska / Morze / Kołobrzeg', 'True', 'Bez wyżywienia,Śniadania,2 posiłki'),
('Regent Warsaw Hotel', 'Polska / W mieście / Warszawa', 'True', 'Śniadania'),
('Hotel Wellness Harrachovka', 'Czechy / Czeskie Karkonosze / Harrachov', 'True', '2 posiłki'),
('Hotel Renaissance Warsaw Airport', 'Polska / Przy lotnisku / Warszawa', 'True', 'Śniadania'),
('Hotel Piotr SPA &Wellness', 'Polska / Góry / Boguszów-gorce', 'True', 'Śniadania,2 posiłki'),
('Hotel Redyk Ski & Relax', 'Polska / Góry / Ząb', 'True', 'Śniadania,2 posiłki'),
('Hotel Srní', 'Czechy / Szumawy / Srni', 'True', 'Śniadania,2 posiłki'),
('Apartamenty Ostróda', 'Polska / Jeziora / Ostróda', 'True', 'Śniadania'),
('NAT Krynica Morska', 'Polska / Morze / Krynica Morska', 'True', 'Śniadania,2 posiłki'),
('Hotel Clarion', 'Czechy (narty) / Czeskie Karkonosze / Szpindlerowy Młyn', 'True', 'Śniadania,2 posiłki'),
('Osada Górski Potok', 'Polska / Góry / Szczawina', 'True', 'Śniadania,2 posiłki,All inclusive'),
('Focus Hotel Gdańsk', 'Polska / Morze / Gdańsk', 'True', 'Śniadania,2 posiłki'),
('Hotel Las', 'Polska / Góry / Piechowice', 'True', 'Śniadania,2 posiłki'),
('Hotel NAT Jarosławiec', 'Polska / Morze / Jarosławiec', 'True', 'Śniadania,2 posiłki'),
('Focus Hotel Premium Sopot', 'Polska / Morze / Sopot', 'True', 'Śniadania,2 posiłki')
